# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.10)
{
  # A helpful description of your flake
  description = "koushinryou website";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*.tar.gz";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*.tar.gz";
  };

  # Flake outputs that other flakes can use
  outputs = inputs: with inputs;
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;
      packages = forEachSupportedSystem ({ pkgs }: rec {
        default = koushinryou;
        koushinryou = pkgs.buildNpmPackage {
          pname = "koushinryou";
          version = "0.0.1";
          src = ./.;
          buildInputs = [
            pkgs.vips
          ];
          nativeBuildInputs = [
            pkgs.pkg-config
          ];
          installPhase = ''
            runHook preInstall
            cp -pr --reflink=auto dist $out/
            runHook postInstall
          '';

          npmDepsHash = "sha256-mFt1xpGwj99j0kzEqR3ZHS/+e8DhqBjVf2lHEtOv0dA=";
        };
      });
      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [
            nodejs
            nodePackages.yarn
            git
            nixpkgs-fmt
          ];
        };
      });
    };
}
